// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: core.proto

package core

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Paginate with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Paginate) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Paginate with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PaginateMultiError, or nil
// if none found.
func (m *Paginate) ValidateAll() error {
	return m.validate(true)
}

func (m *Paginate) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Offset

	// no validation rules for Limit

	// no validation rules for Total

	if len(errors) > 0 {
		return PaginateMultiError(errors)
	}

	return nil
}

// PaginateMultiError is an error wrapping multiple validation errors returned
// by Paginate.ValidateAll() if the designated constraints aren't met.
type PaginateMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PaginateMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PaginateMultiError) AllErrors() []error { return m }

// PaginateValidationError is the validation error returned by
// Paginate.Validate if the designated constraints aren't met.
type PaginateValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PaginateValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PaginateValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PaginateValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PaginateValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PaginateValidationError) ErrorName() string { return "PaginateValidationError" }

// Error satisfies the builtin error interface
func (e PaginateValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPaginate.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PaginateValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PaginateValidationError{}

// Validate checks the field values on Option with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Option) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Option with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in OptionMultiError, or nil if none found.
func (m *Option) ValidateAll() error {
	return m.validate(true)
}

func (m *Option) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Key

	// no validation rules for Value

	if len(errors) > 0 {
		return OptionMultiError(errors)
	}

	return nil
}

// OptionMultiError is an error wrapping multiple validation errors returned by
// Option.ValidateAll() if the designated constraints aren't met.
type OptionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OptionMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OptionMultiError) AllErrors() []error { return m }

// OptionValidationError is the validation error returned by Option.Validate if
// the designated constraints aren't met.
type OptionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OptionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OptionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OptionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OptionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OptionValidationError) ErrorName() string { return "OptionValidationError" }

// Error satisfies the builtin error interface
func (e OptionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOption.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OptionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OptionValidationError{}

// Validate checks the field values on ListOption with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ListOption) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListOption with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ListOptionMultiError, or
// nil if none found.
func (m *ListOption) ValidateAll() error {
	return m.validate(true)
}

func (m *ListOption) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Offset

	// no validation rules for Limit

	// no validation rules for SkipTotal

	for idx, item := range m.GetOptions() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListOptionValidationError{
						field:  fmt.Sprintf("Options[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListOptionValidationError{
						field:  fmt.Sprintf("Options[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListOptionValidationError{
					field:  fmt.Sprintf("Options[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListOptionMultiError(errors)
	}

	return nil
}

// ListOptionMultiError is an error wrapping multiple validation errors
// returned by ListOption.ValidateAll() if the designated constraints aren't met.
type ListOptionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListOptionMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListOptionMultiError) AllErrors() []error { return m }

// ListOptionValidationError is the validation error returned by
// ListOption.Validate if the designated constraints aren't met.
type ListOptionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListOptionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListOptionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListOptionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListOptionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListOptionValidationError) ErrorName() string { return "ListOptionValidationError" }

// Error satisfies the builtin error interface
func (e ListOptionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListOption.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListOptionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListOptionValidationError{}

// Validate checks the field values on RawReq with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RawReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RawReq with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in RawReqMultiError, or nil if none found.
func (m *RawReq) ValidateAll() error {
	return m.validate(true)
}

func (m *RawReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Buf

	if len(errors) > 0 {
		return RawReqMultiError(errors)
	}

	return nil
}

// RawReqMultiError is an error wrapping multiple validation errors returned by
// RawReq.ValidateAll() if the designated constraints aren't met.
type RawReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RawReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RawReqMultiError) AllErrors() []error { return m }

// RawReqValidationError is the validation error returned by RawReq.Validate if
// the designated constraints aren't met.
type RawReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RawReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RawReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RawReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RawReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RawReqValidationError) ErrorName() string { return "RawReqValidationError" }

// Error satisfies the builtin error interface
func (e RawReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRawReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RawReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RawReqValidationError{}

// Validate checks the field values on RawRsp with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RawRsp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RawRsp with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in RawRspMultiError, or nil if none found.
func (m *RawRsp) ValidateAll() error {
	return m.validate(true)
}

func (m *RawRsp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Buf

	// no validation rules for ContentType

	if len(errors) > 0 {
		return RawRspMultiError(errors)
	}

	return nil
}

// RawRspMultiError is an error wrapping multiple validation errors returned by
// RawRsp.ValidateAll() if the designated constraints aren't met.
type RawRspMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RawRspMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RawRspMultiError) AllErrors() []error { return m }

// RawRspValidationError is the validation error returned by RawRsp.Validate if
// the designated constraints aren't met.
type RawRspValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RawRspValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RawRspValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RawRspValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RawRspValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RawRspValidationError) ErrorName() string { return "RawRspValidationError" }

// Error satisfies the builtin error interface
func (e RawRspValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRawRsp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RawRspValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RawRspValidationError{}
